### ISSUE TITLE
MOBA-rally: Should towers reward option card when destroyed?

### ISSUE THREAD

**Issue by GummiWyrms** [tlake/custom-robo-rally#18]
Currently:
> When destroyed, a tower deals 5 damage to its friendly base, and each living enemy robot is awarded an option card.

Proposal: Remove the option card reward. 

Why? 4 options divvied out to a single team is highly unstable, and pushes the momentum of the game further in favor of the side that destroys towers quickly. This will make it easier for teams who destroy towers to continue destroying more towers (and earning more options). Aka, it's a snowball mechanic that isn't required. The reward for destroying the towers should be that a safe path to the enemy base is opened up and 5 damage is dealt to the base. This reward is quite good without being overbearing.

**Comment by nickamante** [comment]
+1 four options seems excessive

**Comment by tlake** [comment]
Seems fine to me; I think it might have been a mechanic for speeding up the game when we felt that we were timeboxed a little harder, but I agree that it overextends into snowball territory. I haven't heard any pushback around, so I'll get this updated sooner rather than later.

**Comment by GummiWyrms** [comment]
We were thinking about the following as well: Instead of 1 option per team member, what about 1 option, given to any of the enemy team robots? 4 options is too much, but a single option, given to one robot of choice, could be a more appropriate reward.

**Comment by tlake** [comment]
Mm, that _also_ sounds like a fine idea. Adds a bit more fun to destroying towers without falling into huge snowball territory.

**Comment by nickamante** [comment]
Say team A destroys team B's tower.
What if instead of awarding options to team A, the destruction of the tower scrambles team Bs team option transmitter (team B discards their global option (if any) and then draws a random one)

I was originally thinking it could just destroy the option (like with the mini howitzer to the base), but replacing it randomly would hurt if their option was strong but might help if it was weak (or none), so it's somewhat self-balancing.

**Comment by tlake** [comment]
In an effort to get this ticket resolved, I'm going to update in alignment with @GummiWyrms' [comment](https://github.com/tlake/robo-rally-variants/issues/18#issuecomment-401133593) to give the offensive team one option to distribute among themselves.
